/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-04-29

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/


#define TRANSFER_U1 1
#define TRANSFER_U2 0

#define BUFFER_SIZE 256
uint8_t transmit_receive_buffer_u1[BUFFER_SIZE];
uint8_t transmit_receive_buffer_u2[BUFFER_SIZE];

uint8_t count_RX = 0;
uint8_t count_TX = 0;

void clear_buffer(uint8_t buf[BUFFER_SIZE]) {
	for(int i = 0; i < BUFFER_SIZE; i++) {
			buf[i] = 0;
		}
}

void USART1_IRQHandler(void) {
	if((USART1->ISR & USART_ISR_RXNE) == USART_ISR_RXNE) {
		transmit_receive_buffer_u1[count_RX] = (uint8_t)USART1->RDR;
		count_RX++;
	}
}

void USART2_IRQHandler(void) {
	if((USART2->ISR & USART_ISR_RXNE) == USART_ISR_RXNE) {
		transmit_receive_buffer_u2[count_RX] = (uint8_t)USART2->RDR;
		count_RX++;
	}
}

void DMA1_Channel4_5_IRQHandler(void) {
	if ((DMA1->ISR & DMA_ISR_TCIF4) == DMA_ISR_TCIF4) {
			DMA1->IFCR |= DMA_IFCR_CTCIF4;
			count_RX = 0;
			count_TX++;
			GPIOC->ODR ^= GPIO_ODR_9;
			clear_buffer(&transmit_receive_buffer_u2[0]);
			DMA1_Channel4->CCR &= ~DMA_CCR_EN;
			DMA1_Channel2->CCR |= DMA_CCR_EN;
	}
}

void DMA1_Channel2_3_IRQHandler(void) {
	if ((DMA1->ISR & DMA_ISR_TCIF2) == DMA_ISR_TCIF2) {
			DMA1->IFCR |= DMA_IFCR_CTCIF2;
			count_RX = 0;
			count_TX++;
			GPIOC->ODR ^= GPIO_ODR_8;
			clear_buffer(&transmit_receive_buffer_u1[0]);
			DMA1_Channel2->CCR &= ~DMA_CCR_EN;
			DMA1_Channel4->CCR |= DMA_CCR_EN;
		}
}

void init_buffers() {
	for(int i = 0; i < BUFFER_SIZE; i++) {
		transmit_receive_buffer_u2[i] = i + 1;
		transmit_receive_buffer_u1[i] = 0;
	}
}

void init_GPIOA(){
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;

	//USART2_TX
	GPIOA->MODER |= GPIO_MODER_MODER2_1;
	//USART2_RX
	GPIOA->MODER |= GPIO_MODER_MODER3_1;
	GPIOA->AFR[0] |= 0x01 << GPIO_AFRL_AFRL2_Pos;
	GPIOA->AFR[0] |= 0x01 << GPIO_AFRL_AFRL3_Pos;

	//USART1_TX
	GPIOA->MODER |= GPIO_MODER_MODER9_1;
	//USART1_RX
	GPIOA->MODER |= GPIO_MODER_MODER10_1;

	GPIOA->AFR[1] |= 0x01 << GPIO_AFRH_AFRH1_Pos;
	GPIOA->AFR[1] |= 0x01 << GPIO_AFRH_AFRH2_Pos;

	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODER8_0;
	GPIOC->MODER |= GPIO_MODER_MODER9_0;
}

void init_USART2() {
	//RCC on
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;

	//pa2
	USART2->CR1 |= USART_CR1_TE;
	//pa3
	USART2->CR1 |= USART_CR1_RE;
	USART2->BRR = SystemCoreClock / 115200;
	USART2->CR1 |= USART_CR1_RXNEIE;
	USART2->CR3 |= USART_CR3_DMAT;
	//USART1 on
	USART2->CR1 |= USART_CR1_UE;

	NVIC_EnableIRQ(USART2_IRQn);
	NVIC_SetPriority(USART2_IRQn, 9);
}

void init_USART1() {
	//RCC on
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;

	//pa10
	USART1->CR1 |= USART_CR1_RE;
	//pa9
	USART1->CR1 |= USART_CR1_TE;
	USART1->BRR = SystemCoreClock / 115200;
	USART1->CR1 |= USART_CR1_RXNEIE;
	USART1->CR3 |= USART_CR3_DMAT;
	//USART1 on
	USART1->CR1 |= USART_CR1_UE;

	NVIC_EnableIRQ(USART1_IRQn);
	NVIC_SetPriority(USART1_IRQn, 9);
}

void init_DMA_to_work_with_USART() {
	RCC->AHBENR |= RCC_AHBENR_DMA1EN;

	//memory increment mode
	DMA1_Channel2->CCR |= DMA_CCR_MINC;
	DMA1_Channel4->CCR |= DMA_CCR_MINC;
	//dir of transfer data
	DMA1_Channel2->CCR |= DMA_CCR_DIR;
	DMA1_Channel4->CCR |= DMA_CCR_DIR;
	//circular mode on
	DMA1_Channel2->CCR |= DMA_CCR_CIRC;
	DMA1_Channel4->CCR |= DMA_CCR_CIRC;
	//size of data in byte
	DMA1_Channel2->CNDTR = 256;
	DMA1_Channel4->CNDTR = 256;
	//address of periphery
	DMA1_Channel2->CPAR = (uint32_t)(&(USART1->TDR));
	DMA1_Channel4->CPAR = (uint32_t)(&(USART2->TDR));
	//address of data
	DMA1_Channel2->CMAR = (uint32_t)(&transmit_receive_buffer_u1[0]);
	DMA1_Channel4->CMAR = (uint32_t)(&transmit_receive_buffer_u2[0]);

	//interrupt on
	DMA1_Channel4->CCR |= DMA_CCR_TCIE;
	NVIC_EnableIRQ(DMA1_Channel4_5_IRQn);
	NVIC_SetPriority(DMA1_Channel4_5_IRQn, 3);

	DMA1_Channel2->CCR |= DMA_CCR_TCIE;
	NVIC_EnableIRQ(DMA1_Channel2_3_IRQn);
	NVIC_SetPriority(DMA1_Channel2_3_IRQn, 3);
	//DMA on
	DMA1_Channel4->CCR |= DMA_CCR_EN;
}


int main(void)
{
  init_buffers();

  init_GPIOA();
  init_USART1();
  init_USART2();
  init_DMA_to_work_with_USART();

  /* TODO - Add your application code here */
  /* Infinite loop */
  while (1)
  {
  }
}
